name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # or "master" if your repo uses master

permissions:
  contents: read
  pages: write       # allow deployment to Pages
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Upload repo root (with index.html) as artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # this includes index.html

  deploy:
    environment:
      name: github-pages   # auto-creates environment if missing
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
